/*
 * This file is distributed under the MIT License. See LICENSE.md for details.
 */

import "./main.css";

import sqlite3InitModule, { Database, SQLite3Error, Sqlite3Static } from "@sqlite.org/sqlite-wasm";
import DataTable, { Api, ConfigColumns } from "datatables.net-dt";
import { Tarball } from "@obsidize/tar-browserify";
import { saveAs } from "file-saver";
import * as yaml from "yaml";
import { basename } from "path";
import { filesize } from "filesize";

// We inject some variables into `window`, for easier debugging
declare global {
    interface Window {
        _sqlite3?: Sqlite3Static;
        db?: Database;
    }
}

// Interface describing the contents of `meta.yml`
interface Metadata {
    extra_columns?: {
        name: string;
        label: string;
        renderer?: string;
        align?: "left" | "right";
    }[];

    downloads?: {
        name: string;
        label: string;
    }[];

    ordering?: {
        name: string;
        dir: "asc" | "desc";
    }[];

    notes?: string;
    reproducer_prelude?: string;
    highlights?: {
        query: string;
        description: string;
    }[];

    configurations?: {
        name?: string;
        timeout?: number;
        memory_limit?: number;
    }[];

    // Autogenerated by `revng mass-testing run`
    cpu_count: number;
    start_time: number;
}

const sqlOptions = { rowMode: "object", returnValue: "resultRows" } as const;

// ---- SQLite bootstrap ----------------------------------------------------

async function initSqlite3(): Promise<Sqlite3Static> {
    if (window._sqlite3 !== undefined) {
        return window._sqlite3;
    } else {
        const sqlite3 = await sqlite3InitModule({
            print: console.log,
            printErr: console.error,
        });
        window._sqlite3 = sqlite3;
        return sqlite3;
    }
}

// Given a URL, load it as an sqlite database and return it
async function loadDBFromURL(url: string | URL): Promise<Database> {
    const sqlite3 = await initSqlite3();
    const req = await fetch(url);
    const buffer = await req.arrayBuffer();
    const db_buffer = sqlite3.wasm.allocFromTypedArray(buffer);
    const db = new sqlite3.oo1.DB();
    const rc = sqlite3.capi.sqlite3_deserialize(
        db,
        "main",
        db_buffer,
        buffer.byteLength,
        buffer.byteLength,
        sqlite3.capi.SQLITE_DESERIALIZE_FREEONCLOSE
    );
    db.checkRc(rc);
    return db;
}

function sleep(time: number): Promise<void> {
    return new Promise((res) => setTimeout(() => res(undefined), time));
}

// ---- Small DOM helper ----------------------------------------------------

// Minimal hyperscript helper. `attrs` supports: class, text, html, style
// (object), on<Event> handlers, and any other key becomes an attribute.
function h(tag: string, attrs?: Record<string, any> | null, ...children: any[]): HTMLElement {
    const e = document.createElement(tag);
    if (attrs) {
        for (const [k, v] of Object.entries(attrs)) {
            if (v === undefined || v === null || v === false) {
                continue;
            } else if (k === "class") {
                e.className = v;
            } else if (k === "text") {
                e.textContent = String(v);
            } else if (k === "html") {
                e.innerHTML = v;
            } else if (k === "style" && typeof v === "object") {
                Object.assign(e.style, v);
            } else if (k.startsWith("on") && typeof v === "function") {
                e.addEventListener(k.slice(2).toLowerCase(), v);
            } else {
                e.setAttribute(k, String(v));
            }
        }
    }
    for (const c of children.flat()) {
        if (c === null || c === undefined || c === false) continue;
        e.append(c instanceof Node ? c : document.createTextNode(String(c)));
    }
    return e;
}

// Inline SVG icons (kept as ASCII source; rendered via innerHTML). All use
// currentColor so they inherit the surrounding text color.
const ICONS: Record<string, string> = {
    dots: '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><circle cx="3" cy="8" r="1.4"/><circle cx="8" cy="8" r="1.4"/><circle cx="13" cy="8" r="1.4"/></svg>',
    search: '<svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="7" cy="7" r="4.3"/><line x1="10.4" y1="10.4" x2="14" y2="14" stroke-linecap="round"/></svg>',
    chevron:
        '<svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 3l5 5-5 5" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    back: '<svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M9 3L4 8l5 5M4.3 8H13" stroke-linecap="round" stroke-linejoin="round"/></svg>',
};

function icon(name: string, cls?: string): HTMLElement {
    return h("span", { class: cls ? `ic ${cls}` : "ic", html: ICONS[name] });
}

// ---- Formatting ----------------------------------------------------------

function truncate(num: number, digits: number): number {
    return Math.trunc(num * 10 ** digits) / 10 ** digits;
}

function percent(num: number, total: number): string {
    return `${truncate((num * 100) / total, 2)}%`;
}

function commas(num: number): string {
    return num.toLocaleString("en-US");
}

function padNumber(num: number, amount: number): string {
    return `${num}`.padStart(amount, "0");
}

function splitHMS(seconds: number): { h: number; m: number; s: number } {
    return {
        h: Math.floor(seconds / 3600),
        m: Math.floor((seconds / 60) % 60),
        s: Math.floor(seconds % 60),
    };
}

// Per-run elapsed time as MM:ss.mmm
function formatTime(seconds: number): string {
    const milliseconds = seconds.toFixed(3).split(".", 2)[1];
    return `${padNumber(Math.floor(seconds / 60), 2)}:${padNumber(
        Math.floor(seconds % 60),
        2
    )}.${milliseconds}`;
}

// hh:mm:ss without milliseconds
function formatClock(seconds: number): string {
    const { h, m, s } = splitHMS(seconds);
    return `${padNumber(h, 2)}:${padNumber(m, 2)}:${padNumber(s, 2)}`;
}

// "41h 57m"
function formatHM(seconds: number): string {
    const { h, m } = splitHMS(seconds);
    return `${h}h ${padNumber(m, 2)}m`;
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// From a UNIX timestamp (seconds), "2026-07-03 15:48:39 UTC"
function formatTimestamp(unixSeconds: number): string {
    return new Date(unixSeconds * 1000).toISOString().replace("T", " ").slice(0, 19) + " UTC";
}

// From a UNIX timestamp (seconds), "Jul 3, 2026"
function formatDatePill(unixSeconds: number): string {
    const d = new Date(unixSeconds * 1000);
    return `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}, ${d.getUTCFullYear()}`;
}

// Extract the (short) commit hash from the free-form `notes` string
function revngVersion(meta: Metadata): string | undefined {
    const match = (meta.notes || "").match(/[0-9a-f]{7,40}/);
    return match ? match[0] : undefined;
}

// ---- Per-status/per-page configuration ----------------------------------

interface PageConfig {
    page: string;
    title: string;
    status?: string; // filter applied to the `main` table
    category?: string; // crash_components category, for stage bars/flamegraphs
    fgPrefix?: string; // flamegraph file prefix
    accent: string; // css accent class, e.g. a-crash
    rowNoun: string; // "crashed binaries"
    fgEnd?: string; // "crash", "timeout", "OOM" location wording
}

const PAGES: Record<string, PageConfig> = {
    overview: { page: "overview", title: "Overview", accent: "a-crash", rowNoun: "binaries" },
    failures: {
        page: "failures",
        title: "Failures",
        status: "FAILED",
        accent: "a-fail",
        rowNoun: "failed binaries",
    },
    crashes: {
        page: "crashes",
        title: "Crashes",
        status: "CRASHED",
        category: "CRASHED",
        fgPrefix: "failures",
        accent: "a-crash",
        rowNoun: "crashed binaries",
        fgEnd: "crash",
    },
    timeouts: {
        page: "timeouts",
        title: "Timeouts",
        status: "TIMED_OUT",
        category: "TIMED_OUT",
        fgPrefix: "timeouts",
        accent: "a-timeout",
        rowNoun: "timed-out binaries",
        fgEnd: "timeout",
    },
    ooms: {
        page: "ooms",
        title: "OOMs",
        status: "OOM",
        category: "OOM",
        fgPrefix: "ooms",
        accent: "a-oom",
        rowNoun: "out-of-memory binaries",
        fgEnd: "OOM",
    },
    successes: {
        page: "successes",
        title: "Successes",
        status: "OK",
        accent: "a-ok",
        rowNoun: "successful binaries",
    },
    raw_data: { page: "raw_data", title: "Raw Data", accent: "a-crash", rowNoun: "binaries" },
};

// Tabs appear in the order the pages are declared in PAGES
const NAV_ORDER = Object.keys(PAGES);

function pageHref(key: string): string {
    return key === "overview" ? "index.html" : `${key}.html`;
}

// ---- Page chrome (top bar + tabs) ---------------------------------------

function buildChrome(root: HTMLElement, meta: Metadata, cfg: PageConfig): HTMLElement {
    const panel = h("div", { class: "panel" });

    const configName = meta.configurations?.[0]?.name ?? "revng mass testing";
    const shortHash = revngVersion(meta)?.slice(0, 7);

    const badges: any[] = [];
    if (meta.start_time) {
        badges.push(h("span", { class: "pill" }, `Report - ${formatDatePill(meta.start_time)}`));
    }
    if (shortHash) {
        badges.push(h("span", { class: "pill mono" }, shortHash));
    }

    const topbar = h(
        "div",
        { class: "topbar" },
        h(
            "div",
            { class: "brand" },
            h("span", { class: "brand-title" }, "Mass Testing"),
            h("span", { class: "brand-sub" }, configName)
        ),
        h("div", { class: "badges" }, ...badges)
    );

    const tabs = h("div", { class: `tabs ${cfg.accent}` });
    for (const key of NAV_ORDER) {
        const active = key === cfg.page;
        const a = h(
            "a",
            { href: pageHref(key), class: active ? "active" : "" },
            PAGES[key].title
        );
        tabs.append(a);
    }

    const content = h("div", { class: "content" });
    panel.append(topbar, tabs, content);
    root.append(panel);
    return content;
}

// ---- Data helpers --------------------------------------------------------

interface StatusStats {
    total: number;
    totalTime: number;
    counts: Record<string, number>;
}

// Per-status counts (plus totals) in a single grouped scan, so callers do not
// need to know the set of statuses ahead of time.
function statusStats(db: Database): StatusStats {
    const rows = db.exec({
        sql: "SELECT status, COUNT(*) AS n, SUM(elapsed_time) AS t FROM main GROUP BY status",
        ...sqlOptions,
    });
    const counts: Record<string, number> = {};
    let total = 0;
    let totalTime = 0;
    for (const r of rows) {
        counts[r.status as string] = r.n as number;
        total += r.n as number;
        totalTime += (r.t as number) || 0;
    }
    return { total, totalTime, counts };
}

function statusCount(s: StatusStats, status: string): number {
    return s.counts[status] ?? 0;
}

function distinctSignatures(db: Database, status: string): number {
    const rows = db.exec({
        sql: "SELECT COUNT(DISTINCT stacktrace_id) AS n FROM main WHERE status = ? AND stacktrace_id != ''",
        bind: [status],
        ...sqlOptions,
    });
    return (rows[0]?.n as number) ?? 0;
}

interface StageEntry {
    name: string;
    count: number;
}

function stageEntries(db: Database, category: string, filter: string): StageEntry[] {
    const rows = db.exec({
        sql: "SELECT name, count FROM crash_components WHERE category = ? AND filter = ?",
        bind: [category, filter],
        ...sqlOptions,
    });
    const entries = rows.map((r) => ({ name: r.name as string, count: r.count as number }));
    entries.sort((a, b) => b.count - a.count);
    return entries;
}

function stageFilters(db: Database, category: string): string[] {
    const rows = db.exec({
        sql: "SELECT DISTINCT filter FROM crash_components WHERE category = ?",
        bind: [category],
        ...sqlOptions,
    });
    const filters = rows.map((r) => r.filter as string);
    // Put "all" first, then percentiles in ascending order
    filters.sort((a, b) => {
        if (a === "all") return -1;
        if (b === "all") return 1;
        const na = parseInt(a, 10) || 0;
        const nb = parseInt(b, 10) || 0;
        return na - nb;
    });
    return filters;
}

// Human label for a crash_components filter value
function filterLabel(filter: string): string {
    if (filter === "all") {
        return "all sizes";
    }
    const m = filter.match(/^(\d+)th_percentile_on_(.+)$/);
    if (m) {
        const variable = m[2] === "text_size" ? ".text" : m[2];
        return `smallest ${m[1]}% (${variable})`;
    }
    return filter;
}

// ---- Bar lists -----------------------------------------------------------

function renderBars(entries: StageEntry[], limit: number, twoCol: boolean): HTMLElement {
    const shown = entries.slice(0, limit);
    const total = entries.reduce((a, e) => a + e.count, 0) || 1;
    const max = Math.max(1, ...shown.map((e) => e.count));

    const container = h("div", { class: twoCol ? "bars two-col" : "bars" });
    for (const e of shown) {
        const bar = h(
            "div",
            { class: "bar" },
            h(
                "div",
                { class: "bar-top" },
                h("span", { class: "bar-name", title: e.name }, e.name),
                h(
                    "span",
                    { class: "bar-val" },
                    `${commas(e.count)} - ${percent(e.count, total)}`
                )
            ),
            h(
                "div",
                { class: "bar-track" },
                h("div", {
                    class: "bar-fill",
                    style: { width: `${(e.count / max) * 100}%` },
                })
            )
        );
        container.append(bar);
    }
    return container;
}

// A block with a title, an optional percentile dropdown and a bars list that
// re-renders when the dropdown changes. Used both on the overview (one column
// per category) and on the detail pages. `onFilter` lets callers hook extra
// updates (e.g. swapping the flamegraph on detail pages).
interface StageBlock {
    pctlRow?: HTMLElement; // the "Binary size" label + dropdown, when >1 filter
    barsHost: HTMLElement;
    initialFilter: string;
    count: number; // number of stages at the initial filter
}

function stageBlock(
    db: Database,
    category: string,
    opts: { limit: number; twoCol: boolean; onFilter?: (filter: string) => void }
): StageBlock {
    const filters = stageFilters(db, category);
    const initialFilter = filters.includes("all") ? "all" : filters[0];
    const barsHost = h("div", {});

    const renderFilter = (filter: string) => {
        barsHost.innerHTML = "";
        barsHost.append(renderBars(stageEntries(db, category, filter), opts.limit, opts.twoCol));
    };
    const initialEntries = stageEntries(db, category, initialFilter);
    barsHost.append(renderBars(initialEntries, opts.limit, opts.twoCol));

    let pctlRow: HTMLElement | undefined;
    if (filters.length > 1) {
        const select = h("select", { class: "pctl" }) as HTMLSelectElement;
        for (const f of filters) {
            const option = h("option", { value: f }, filterLabel(f)) as HTMLOptionElement;
            if (f === initialFilter) option.selected = true;
            select.append(option);
        }
        select.addEventListener("change", () => {
            renderFilter(select.value);
            opts.onFilter?.(select.value);
        });
        pctlRow = h(
            "div",
            { class: "pctl-row" },
            h("span", { class: "lbl" }, "Binary size"),
            select
        );
    }

    return { pctlRow, barsHost, initialFilter, count: initialEntries.length };
}

// ---- Flamegraphs ---------------------------------------------------------

function flamegraphImages(prefix: string, filter: string, end: string): HTMLElement {
    const host = h("div", { class: "fg-images" });
    const variants: [string, string][] = [
        ["bottomup", `Bottom up - ${end} location at the top`],
        ["topdown", "Top down - thread entry point at the bottom"],
    ];
    for (const [type, caption] of variants) {
        const base = filter === "all" ? `${prefix}_${type}` : `${prefix}_${filter}_${type}`;
        const anchor = h("a", { href: `${base}.svg`, target: "_blank", title: caption });
        anchor.append(h("img", { src: `${base}.png`, alt: caption, loading: "lazy" }));
        host.append(anchor);
    }
    return host;
}

// ---- Perfetto / reproducer (unchanged behaviour) -------------------------

async function openPerfetto(name: string, trace: string): Promise<void> {
    const req_promise = fetch(trace);
    const handle = window.open("https://ui.perfetto.dev", "_blank");
    if (handle === null) {
        return;
    }
    let ponged = false;
    window.addEventListener("message", function listener(ev) {
        if (ev.data === "PONG") {
            ponged = true;
            window.removeEventListener("message", listener);
        }
    });
    for (;;) {
        handle.postMessage("PING", "*");
        await sleep(100);
        if (ponged) {
            break;
        }
    }
    const req = await req_promise;
    if (!req.ok) {
        return;
    }
    handle.postMessage(
        {
            perfetto: {
                buffer: await req.arrayBuffer(),
                title: `Trace of ${name}`,
                fileName: basename(trace),
            },
        },
        "*"
    );
}

async function createReproducer(name: string, meta: Metadata): Promise<Uint8Array | undefined> {
    const binReq = await fetch(`${name}/input`);
    if (!binReq.ok) {
        return undefined;
    }
    const tarball = new Tarball();
    tarball.addBinaryFile("input", new Uint8Array(await binReq.arrayBuffer()), { fileMode: 0o444 });

    const commandReq = await fetch(`${name}/test-harness.json`);
    const command: string[] = (await commandReq.json()).command;

    for (let i = 0; i < command.length; i++) {
        if (command[i] == "%INPUT%") {
            command[i] = "input";
        }
    }

    const script = `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$(realpath "$(dirname "\${BASH_SOURCE[0]}")")

${meta.reproducer_prelude || ""}

${command.join(" ")} "$@"
`;
    tarball.addTextFile("go.sh", script, { fileMode: 0o555 });

    return tarball.toUint8Array();
}

// ---- Row action menu (...) ----------------------------------------------

interface ActionItem {
    label: string;
    strong?: boolean;
    run: () => void;
}

let currentMenu: HTMLElement | null = null;

function closeActionMenu() {
    if (currentMenu !== null) {
        currentMenu.remove();
        currentMenu = null;
        document.removeEventListener("click", onDocClick, true);
        document.removeEventListener("scroll", closeActionMenu, true);
        window.removeEventListener("resize", closeActionMenu);
    }
}

function onDocClick(ev: MouseEvent) {
    if (currentMenu !== null && !currentMenu.contains(ev.target as Node)) {
        closeActionMenu();
    }
}

function openActionMenu(anchor: HTMLElement, items: ActionItem[]) {
    const wasOpen = currentMenu;
    closeActionMenu();
    if (wasOpen !== null && anchor.dataset.menuId === wasOpen.dataset.menuId) {
        return; // toggling the same button off
    }

    const menu = h("div", { class: "action-menu" });
    const menuId = String(Math.floor(performance.now() * 1000));
    menu.dataset.menuId = menuId;
    anchor.dataset.menuId = menuId;

    for (const item of items) {
        if (item.label === "-") {
            menu.append(h("div", { class: "sep" }));
            continue;
        }
        menu.append(
            h(
                "button",
                {
                    class: `action-item${item.strong ? " strong" : ""}`,
                    onClick: () => {
                        closeActionMenu();
                        item.run();
                    },
                },
                item.label
            )
        );
    }

    const r = anchor.getBoundingClientRect();
    menu.style.top = `${r.bottom + 5}px`;
    menu.style.left = "auto";
    menu.style.right = `${window.innerWidth - r.right}px`;

    document.body.append(menu);
    currentMenu = menu;
    // Defer listener registration so the opening click does not close it
    setTimeout(() => {
        document.addEventListener("click", onDocClick, true);
        document.addEventListener("scroll", closeActionMenu, true);
        window.addEventListener("resize", closeActionMenu);
    }, 0);
}

function downloadUrl(url: string, filename?: string) {
    const a = document.createElement("a");
    a.href = url;
    if (filename) a.download = filename;
    document.body.append(a);
    a.click();
    a.remove();
}

function rowActions(row: any, meta: Metadata, inDetail: boolean): ActionItem[] {
    const name: string = row.name;
    const items: ActionItem[] = [
        { label: "Download binary", run: () => downloadUrl(`${name}/input`, row.input_name) },
        { label: "View log", run: () => window.open(`${name}/output.log`, "_blank") },
    ];
    for (const dl of meta.downloads || []) {
        items.push({ label: dl.label, run: () => window.open(`${name}/${dl.name}`, "_blank") });
    }
    if (row.has_trace) {
        const trace = `${name}/trace.json.gz`;
        items.push({ label: "Download trace", run: () => downloadUrl(trace) });
        items.push({ label: "Open in Perfetto", run: () => openPerfetto(name, trace) });
    }
    items.push({
        label: "Reproduce",
        run: async () => {
            const tar = await createReproducer(name, meta);
            if (tar !== undefined) {
                saveAs(
                    new Blob([tar as any], { type: "application/tar" }),
                    `${basename(name)}-reproducer.tar`
                );
            }
        },
    });
    items.push({ label: "All files", run: () => window.open(`${name}/`, "_blank") });
    if (!inDetail) {
        items.push({ label: "-", run: () => {} });
        items.push({
            label: "Open details",
            strong: true,
            run: () => {
                window.location.href = `binary.html#${name}`;
            },
        });
    }
    return items;
}

function actionsButton(row: any, meta: Metadata, inDetail: boolean): HTMLElement {
    const btn = h("button", { class: "actions-btn", title: "Actions" }, icon("dots"));
    btn.addEventListener("click", (ev) => {
        ev.stopPropagation();
        openActionMenu(btn, rowActions(row, meta, inDetail));
    });
    return h("div", { style: { display: "flex", justifyContent: "flex-end" } }, btn);
}

// ---- Renderers -----------------------------------------------------------

const RENDERERS: Record<string, (data: any, type: string) => any> = {
    time: (data: number, type) => (type === "display" ? formatTime(data) : data),
    filesize: (data: number, type) =>
        type !== "display" ? data : data < 0 ? "-" : filesize(data, { base: 2 }),
    ellipsis: (data: string, type) => {
        if (type !== "display") {
            return data;
        }
        return data.length < 70 ? data : data.slice(0, 70) + "...";
    },
};

interface Columns extends ConfigColumns {
    data?: string;
    render?: (data: any, type: string, row: any) => any;
    useRenderForDetail?: boolean;
}

interface TableContext {
    setSearch: (query: string) => void;
}

function getColumns(meta: Metadata, ctx: TableContext, inDetail: boolean): Columns[] {
    const cols: Columns[] = [
        {
            name: "name",
            data: "name",
            title: "Name",
            render: (data: string) => {
                const span = h("span", { class: "cell-name", title: data }, data);
                return span;
            },
            useRenderForDetail: false,
        },
        {
            name: "elapsed_time",
            data: "elapsed_time",
            title: "Time",
            className: "dt-right mono",
            render: RENDERERS["time"],
        },
        { name: "exit_code", data: "exit_code", title: "Exit", className: "dt-right mono" },
        {
            name: "status",
            data: "status",
            title: "Status",
            render: (data: string, type) => {
                if (type !== "display") return data;
                return h("span", { class: `badge badge-${data}` }, data);
            },
        },
        {
            name: "stacktrace_id",
            data: "stacktrace_id",
            title: "Stacktrace",
            orderable: false,
            render: (data: string, type) => {
                if (type !== "display" || data === "") return data;
                const link = h("span", { class: "cell-st", title: "Filter by this stacktrace" }, data);
                link.addEventListener("click", () => ctx.setSearch(data));
                return link;
            },
        },
    ];

    for (const elem of meta.extra_columns || []) {
        const col: Columns = { name: elem.name, data: elem.name, title: elem.label };
        if (elem.renderer !== undefined) {
            col.render = RENDERERS[elem.renderer];
        }
        col.className = `dt-${elem.align ?? "left"} mono`;
        cols.push(col);
    }

    cols.push({
        title: "Actions",
        orderable: false,
        className: "dt-right",
        render: (_data, _type, row) => actionsButton(row, meta, inDetail),
    });

    return cols;
}

// Search state persisted in the location hash
class SearchState {
    public query: string;
    public sql: boolean;

    constructor(query: string, sql: boolean) {
        this.query = query;
        this.sql = sql;
    }

    toString() {
        return btoa(JSON.stringify(this));
    }

    static fromString(data: string): SearchState {
        const obj = JSON.parse(atob(data));
        return new SearchState(obj.query, obj.sql);
    }
}

// Builds the styled data table card and wires search / SQL / pagination
function buildTable(host: HTMLElement, db: Database, meta: Metadata, cfg: PageConfig) {
    const tableCard = h("div", { class: "table-card" });
    const table = h("table", { class: "compact", style: { width: "100%" } });
    tableCard.append(table);
    host.append(tableCard);

    let baseQuery = "SELECT * FROM main WHERE 1=1";
    if (cfg.status) {
        baseQuery += ` AND status = '${cfg.status}'`;
    }

    const getData = (sql: string) => db.exec({ sql, ...sqlOptions });
    // The base (unfiltered) rows never change, so fetch them once and reuse for
    // the initial table, the row count and the SQL-off reset.
    const baseData = getData(baseQuery);

    const ctx: TableContext = { setSearch: () => {} };

    // Title (top-left)
    const titleNode = h("div", { class: "table-title" }, `${commas(baseData.length)} ${cfg.rowNoun}`);

    // Search + SQL toggle (top-right)
    const searchInput = h("input", {
        type: "search",
        placeholder: "Search name, stacktrace id...",
    }) as HTMLInputElement;
    const sqlCheckbox = h("input", { type: "checkbox" }) as HTMLInputElement;
    const sqlToggle = h(
        "label",
        { class: "sql-toggle", title: "Toggle raw SQL WHERE-clause search" },
        sqlCheckbox,
        "SQL"
    );
    const searchNode = h(
        "div",
        { class: "table-search" },
        h(
            "div",
            { class: "searchbox" },
            h("span", { class: "icon", html: ICONS["search"] }),
            searchInput
        ),
        sqlToggle
    );

    const dt: Api<any> = new DataTable(table, {
        data: baseData,
        columns: getColumns(meta, ctx, false) as ConfigColumns[],
        order: meta.ordering as any,
        pageLength: 10,
        layout: {
            topStart: (() => titleNode) as unknown as null,
            topEnd: (() => searchNode) as unknown as null,
            bottomStart: "info",
            bottomEnd: "paging",
        },
    });

    function runSearch(state: SearchState) {
        if (state.sql) {
            let data;
            try {
                data = getData(`${baseQuery} AND (${state.query})`);
            } catch (e) {
                if (e instanceof SQLite3Error) {
                    return;
                }
                throw e;
            }
            dt.clear();
            dt.rows.add(data);
        } else {
            dt.search(state.query);
        }
        dt.draw();
    }

    function updateState(): SearchState {
        const state = new SearchState(searchInput.value, sqlCheckbox.checked);
        window.location.hash = `#${state.toString()}`;
        return state;
    }

    ctx.setSearch = (query: string) => {
        sqlCheckbox.checked = false;
        sqlToggle.classList.remove("on");
        searchInput.value = query;
        runSearch(updateState());
    };

    // Restore a persisted search from the hash
    if (window.location.hash.startsWith("#")) {
        try {
            const state = SearchState.fromString(window.location.hash.slice(1));
            sqlCheckbox.checked = state.sql;
            sqlToggle.classList.toggle("on", state.sql);
            searchInput.value = state.query;
            runSearch(state);
        } catch {
            /* ignore malformed hash */
        }
    }

    sqlCheckbox.addEventListener("input", () => {
        sqlToggle.classList.toggle("on", sqlCheckbox.checked);
        if (sqlCheckbox.checked) {
            dt.search("");
        } else {
            dt.clear();
            dt.rows.add(baseData);
        }
        dt.draw();
        updateState();
    });

    searchInput.addEventListener("input", () => {
        if (!sqlCheckbox.checked) {
            runSearch(updateState());
        }
    });

    searchInput.addEventListener("keyup", (ev: KeyboardEvent) => {
        if (sqlCheckbox.checked && (ev.key === "Enter" || ev.keyCode === 13)) {
            runSearch(updateState());
        }
    });
}

// ---- Overview page -------------------------------------------------------

function renderOverview(content: HTMLElement, db: Database, meta: Metadata) {
    const s = statusStats(db);
    const n = (status: string) => statusCount(s, status);

    // KPI cards
    const kpis = h("div", { class: "kpi-grid" });
    const okPct = ((n("OK") * 100) / s.total).toFixed(1);
    kpis.append(
        h(
            "div",
            { class: "kpi hero" },
            h("div", { class: "kpi-name" }, "Success rate"),
            h(
                "div",
                { class: "big" },
                h("span", { class: "num" }, okPct),
                h("span", { class: "pct" }, "%")
            ),
            h("div", { class: "kpi-sub" }, `${commas(n("OK"))} / ${commas(s.total)} binaries`)
        )
    );

    const kpiDefs: [string, number, string, string | null][] = [
        ["Failures", n("FAILED"), "a-fail", null],
        ["Crashes", n("CRASHED"), "a-crash", "crashes.html"],
        ["Timeouts", n("TIMED_OUT"), "a-timeout", "timeouts.html"],
        ["OOMs", n("OOM"), "a-oom", "ooms.html"],
    ];
    for (const [label, value, accent, href] of kpiDefs) {
        const card = h(
            "div",
            { class: `kpi accent ${accent}${href ? " link" : ""}` },
            h(
                "div",
                { class: "kpi-top" },
                h("span", { class: "kpi-name" }, label),
                href ? icon("chevron", "chev") : null
            ),
            h("div", { class: "kpi-value" }, commas(value)),
            h("div", { class: "kpi-sub kpi-value-accent" }, percent(value, s.total))
        );
        if (href) {
            card.addEventListener("click", () => (window.location.href = href));
        }
        kpis.append(card);
    }
    content.append(kpis);

    // Run composition bar
    const comp: [string, number, string][] = [
        ["Successes", n("OK"), "var(--ok)"],
        ["Timeouts", n("TIMED_OUT"), "var(--timeout)"],
        ["Crashes", n("CRASHED"), "var(--crash)"],
        ["OOMs", n("OOM"), "var(--oom)"],
        ["Failures", n("FAILED"), "var(--fail)"],
    ];
    const compBar = h("div", { class: "comp-bar" });
    const legend = h("div", { class: "comp-legend" });
    for (const [label, value, color] of comp) {
        compBar.append(
            h("span", {
                style: { width: percent(value, s.total), background: color },
                title: `${label}: ${commas(value)}`,
            })
        );
        legend.append(
            h(
                "div",
                { class: "item" },
                h("span", { class: "swatch", style: { background: color } }),
                label,
                h("span", { class: "v" }, percent(value, s.total))
            )
        );
    }
    const runtime = meta.cpu_count ? s.totalTime / meta.cpu_count : s.totalTime;
    content.append(
        h(
            "div",
            { class: "card composition" },
            h(
                "div",
                { class: "comp-head" },
                h("span", { class: "title" }, "Run composition"),
                h(
                    "span",
                    { class: "meta" },
                    `${commas(s.total)} binaries - ${formatHM(runtime)} on ${meta.cpu_count} CPUs`
                )
            ),
            compBar,
            legend
        )
    );

    // Failure breakdown by pipeline stage
    content.append(
        h(
            "div",
            { class: "section-head" },
            h("span", { class: "title" }, "Failure breakdown by pipeline stage"),
            h(
                "span",
                { class: "hint" },
                "Ranked by count - timeouts & OOMs filterable by binary size"
            )
        )
    );

    const cols = h("div", { class: "stage-cols" });
    const stageDefs: [string, string, string][] = [
        ["Crashes", "CRASHED", "a-crash"],
        ["Timeouts", "TIMED_OUT", "a-timeout"],
        ["OOMs", "OOM", "a-oom"],
    ];
    const STAGE_LIMIT = 6;
    for (const [label, category, accent] of stageDefs) {
        const block = stageBlock(db, category, { limit: STAGE_LIMIT, twoCol: false });

        const head = h(
            "div",
            { class: "stage-card-head" },
            h("span", { class: "dot" }),
            h("span", { class: "stage-card-title" }, label),
            h("span", { class: "stage-card-count" }, commas(statusCount(s, category)))
        );

        const card = h("div", { class: `card stage-card ${accent}` }, head);
        if (block.pctlRow) {
            card.append(block.pctlRow);
        }
        card.append(block.barsHost);
        if (block.count > STAGE_LIMIT) {
            card.append(
                h("div", { class: "stage-more" }, `+ ${block.count - STAGE_LIMIT} more stages`)
            );
        }
        cols.append(card);
    }
    content.append(cols);

    // Notable binaries + run details
    const twoGrid = h("div", { class: "two-grid" });

    const notable = h("div", { class: "card" }, h("div", { class: "card-label" }, "Notable binaries"));
    const notableList = h("div", { class: "notable-list" });
    for (const entry of meta.highlights || []) {
        const rows = db.exec({ sql: `SELECT name FROM main ${entry.query} LIMIT 1`, ...sqlOptions });
        // Colour the badge by the status the highlight query filters on, rather
        // than matching the free-form description text.
        const statusMatch = entry.query.match(/status\s*=\s*'(\w+)'/);
        const badgeClass = statusMatch ? `badge-${statusMatch[1]}` : "badge-CRASHED";
        const shortDesc = entry.description.replace(" binary", "");
        const value =
            rows.length > 0
                ? h("a", { href: `binary.html#${rows[0].name}`, title: rows[0].name }, rows[0].name)
                : h("span", { class: "mono", style: { color: "var(--muted)" } }, "N/A");
        notableList.append(
            h(
                "div",
                { class: "notable-item" },
                h("span", { class: `tag badge ${badgeClass}` }, shortDesc),
                value
            )
        );
    }
    notable.append(notableList);
    twoGrid.append(notable);

    const details = h("div", { class: "card" }, h("div", { class: "card-label" }, "Run details"));
    const kv = h("div", { class: "kv" });
    const addKv = (k: string, v: string) => {
        kv.append(h("span", { class: "k" }, k), h("span", { class: "v" }, v));
    };
    if (meta.start_time) addKv("Started", formatTimestamp(meta.start_time));
    addKv("Runtime", `${formatClock(runtime)} - ${meta.cpu_count} CPUs`);
    const version = revngVersion(meta);
    if (version) addKv("revng version", version);
    details.append(kv);
    twoGrid.append(details);

    content.append(twoGrid);
}

// ---- Detail pages (crashes / timeouts / ooms) ---------------------------

// Big count + percentage card shown at the top of detail and list pages.
function summaryCard(cfg: PageConfig, count: number, total: number, note?: string): HTMLElement {
    return h(
        "div",
        { class: `summary-card ${cfg.accent}` },
        h(
            "div",
            { class: "row" },
            h("span", { class: "dot" }),
            h("span", { class: "name" }, cfg.title)
        ),
        h(
            "div",
            { class: "big" },
            h("span", { class: "num" }, commas(count)),
            h("span", { class: "pct" }, percent(count, total))
        ),
        note ? h("div", { class: "note" }, note) : null
    );
}

function renderDetail(content: HTMLElement, db: Database, meta: Metadata, cfg: PageConfig) {
    const s = statusStats(db);
    const count = statusCount(s, cfg.status!);
    const nSig = distinctSignatures(db, cfg.status!);

    // Summary note
    let note = `across ${commas(nSig)} stacktraces`;
    const conf = meta.configurations?.[0];
    if (cfg.status === "CRASHED") {
        note = `across ${commas(nSig)} crash signatures`;
    } else if (cfg.status === "TIMED_OUT" && conf?.timeout) {
        note = `${conf.timeout} s wall-clock limit - ${commas(nSig)} stacktraces`;
    } else if (cfg.status === "OOM" && conf?.memory_limit) {
        note = `${filesize(conf.memory_limit, { base: 2 })} memory limit - ${commas(nSig)} stacktraces`;
    }

    // Summary card + stage breakdown
    const summary = summaryCard(cfg, count, s.total, note);

    // The flamegraph card is created first so the stage block can update it
    const fgHost = h("div", {});
    const updateFlamegraph = (filter: string) => {
        fgHost.innerHTML = "";
        fgHost.append(flamegraphImages(cfg.fgPrefix!, filter, cfg.fgEnd!));
    };

    const block = stageBlock(db, cfg.category!, {
        limit: 8,
        twoCol: true,
        onFilter: updateFlamegraph,
    });
    updateFlamegraph(block.initialFilter);

    const stageHead = h(
        "div",
        { class: "comp-head", style: { marginBottom: "14px" } },
        h("span", { class: "card-label" }, "By pipeline stage")
    );
    if (block.pctlRow) {
        stageHead.append(block.pctlRow);
    }
    const stageCard = h("div", { class: `card ${cfg.accent}` }, stageHead, block.barsHost);

    content.append(h("div", { class: "summary-grid" }, summary, stageCard));

    // Flamegraphs card
    content.append(
        h(
            "div",
            { class: "fg-card" },
            h("div", { class: "fg-title" }, "Flamegraphs"),
            h(
                "div",
                { class: "fg-hint" },
                `Aggregated stack traces - ${cfg.fgEnd} location at the top`
            ),
            fgHost
        )
    );

    // Data table
    buildTable(content, db, meta, cfg);
}

// ---- Plain list pages (failures / successes / raw data) -----------------

function renderList(content: HTMLElement, db: Database, meta: Metadata, cfg: PageConfig) {
    const s = statusStats(db);

    if (cfg.page === "raw_data") {
        content.append(
            h(
                "div",
                { class: "section-head", style: { marginTop: "0" } },
                h("span", { class: "title" }, "Raw data"),
                h("a", { href: "main.db", download: "main.db" }, "Download raw DB")
            )
        );
    } else if (cfg.status) {
        content.append(
            h(
                "div",
                { class: "summary-grid", style: { gridTemplateColumns: "1fr" } },
                summaryCard(cfg, statusCount(s, cfg.status), s.total)
            )
        );
    }

    buildTable(content, db, meta, cfg);
}

// ---- Binary detail page --------------------------------------------------

function renderBinaryDetail(root: HTMLElement, db: Database, meta: Metadata) {
    const hash = window.location.hash;
    if (!hash.startsWith("#")) {
        return;
    }
    const name = hash.slice(1);
    document.getElementsByTagName("title")[0].innerHTML += ` ${name}`;

    const rows = db.exec({ sql: "SELECT * FROM main WHERE name = ?", bind: [name], ...sqlOptions });
    const container = h("div", { class: "app" });
    const panel = h("div", { class: "panel" });
    const content = h("div", { class: "content" });
    panel.append(content);
    container.append(panel);
    root.append(container);

    content.append(
        h(
            "div",
            { class: "topbar", style: { padding: "0 0 18px", background: "transparent", border: "0" } },
            h(
                "div",
                { class: "brand" },
                h(
                    "a",
                    {
                        href: "index.html",
                        class: "brand-sub back-link",
                    },
                    icon("back"),
                    "Mass Testing"
                )
            )
        )
    );

    if (rows.length === 0) {
        content.append(h("h2", { class: "detail-title" }, `No data for ${name}`));
        return;
    }
    const data: Record<string, any> = rows[0];

    content.append(h("h2", { class: "detail-title" }, name));

    const ctx: TableContext = { setSearch: () => {} };
    const table = h("table", { class: "detail-table" });
    const tbody = h("tbody");
    table.append(tbody);
    for (const column of getColumns(meta, ctx, true)) {
        if (column.title === "Actions") continue;
        const tr = h("tr");
        const key = column.title || column.name || "";
        const tdKey = h("th", {}, String(key));
        const tdValue = h("td", {});
        const colData = data[(column as any).data as string];
        if (column.render !== undefined && (column.useRenderForDetail ?? true)) {
            const cell = column.render(colData, "display", data);
            if (cell instanceof HTMLElement) {
                tdValue.append(cell);
            } else {
                tdValue.innerHTML = cell;
            }
        } else {
            tdValue.textContent = colData === undefined || colData === null ? "" : String(colData);
        }
        tr.append(tdKey, tdValue);
        tbody.append(tr);
    }
    // Actions row
    const trActions = h("tr");
    trActions.append(h("th", {}, "Actions"), h("td", {}, actionsButton(data, meta, true)));
    tbody.append(trActions);

    content.append(table);
}

// ---- Entrypoint ----------------------------------------------------------

async function main() {
    const db = await loadDBFromURL("main.db");
    window.db = db;

    const metaReq = await fetch("meta.yml");
    const meta: Metadata = yaml.parse(await metaReq.text());

    // Binary detail is a standalone page
    const detailRoot = document.getElementById("binary-detail");
    if (detailRoot !== null) {
        renderBinaryDetail(detailRoot, db, meta);
        return;
    }

    const pageRoot = document.getElementById("page");
    if (pageRoot === null) {
        return;
    }
    const pageKey = pageRoot.getAttribute("data-page") || "overview";
    const cfg = PAGES[pageKey] || PAGES["overview"];
    const content = buildChrome(pageRoot, meta, cfg);

    if (cfg.page === "overview") {
        renderOverview(content, db, meta);
    } else if (cfg.category) {
        renderDetail(content, db, meta, cfg);
    } else {
        renderList(content, db, meta, cfg);
    }
}

main().then(() => {});
