/*
 * This file is distributed under the MIT License. See LICENSE.md for details.
 */

import { ComponentChild } from "preact";

// Interface describing the contents of `meta.yml`
export interface Metadata {
    extra_columns?: {
        name: string;
        label: string;
        renderer?: string;
        align?: "left" | "right";
    }[];

    downloads?: {
        name: string;
        label: string;
    }[];

    ordering?: {
        name: string;
        dir: "asc" | "desc";
    }[];

    notes?: string;
    reproducer_prelude?: string;
    highlights?: {
        query: string;
        description: string;
    }[];

    configurations?: {
        name?: string;
        timeout?: number;
        memory_limit?: number;
    }[];

    // Autogenerated by `revng mass-testing run`
    cpu_count: number;
    start_time: number;
}

export interface StatusStats {
    total: number;
    totalTime: number;
    counts: Record<string, number>;
}

export interface StageEntry {
    name: string;
    count: number;
}

// A table column definition. `cell` produces the (Preact) content shown in the
// display cell; it is reused both by the DataTables wrapper and the binary
// detail page. When `cell` is omitted the raw value is shown as text.
export interface ColumnDef {
    name: string;
    data?: string;
    title: string;
    className?: string;
    orderable?: boolean;
    searchable?: boolean;
    cell?: (value: any, row: any) => ComponentChild;
    // Whether the binary detail page uses `cell` (default true)
    useCellForDetail?: boolean;
}

// A per-row action shown in the "..." menu
export interface ActionItem {
    label: string;
    strong?: boolean;
    run: () => void;
}
